### ISSUE TITLE
Include via composer

### ISSUE THREAD

**Issue by coxy17** [acato-plugins/wp-rest-cache#19]
Hi, I was just wondering, i am making a personal plugin and wanted to automatically include your plugin as an asset via composer. Is this possible or has the plugin got to be activated via Wordpress plugin directory?

thanks

**Comment by richardkorthuis** [comment]
Hi @coxy17 

You could use WPackagist to include any plugin via composer, including ours: https://wpackagist.org/search?q=wp-rest-cache&type=any&search=
